# Generated by Django 5.0 on 2024-01-15 16:10

import station.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("station", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="train",
            name="image",
            field=models.ImageField(
                null=True, upload_to=station.models.train_image_file_path
            ),
        ),
    ]
