# Generated by Django 4.0.4 on 2024-01-16 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0003_train_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='train',
            options={'ordering': ['name']},
        ),
    ]
